### ISSUE TITLE
bld.sh executable flag not set

### ISSUE THREAD

**Issue by gawbul** [jlinoff/gcc-4.8.4-boost-1.57#1]
Get a permission denied error when trying to run make straight after clone the repo. Need to chmod a+x bld.sh to get it to run.

**Comment by jlinoff** [comment]
Thanks for pointing that out. I thought that I set that in github but will try again.

**Comment by jlinoff** [comment]
I updated the documentation to specify that chmod must be specified. I don't see an easy way to change the permissions from the web interface and I don't have access to my linux box at the moment.

**Comment by gawbul** [comment]
Cool, thanks :smile:

**Comment by jlinoff** [comment]
It is now executable.
