### ISSUE TITLE
mpfr url incorrect

### ISSUE THREAD

**Issue by gawbul** [jlinoff/gcc-4.8.4-boost-1.57#2]
Need to change the mpfr url from http://mpfr.loria.fr/mpfr-current/mpfr-3.1.2.tar.bz2 to http://mpfr.loria.fr/mpfr-3.1.2/mpfr-3.1.2.tar.bz2 (mpfr-current is now 3.1.3).

**Comment by jlinoff** [comment]
Great, thank you. The change has been made.

**Comment by gawbul** [comment]
Thanks @jlinoff :+1:
